name: main

on:
  workflow_dispatch:

jobs:
  upload-container-included-scripts:
    runs-on: ubuntu-latest
    environment: artifacts
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        app-dir: ["apple-store-connect-reporting"]
    steps:
      - name: set-env
        run: |
          APP_DIR=${{ matrix.app-dir }}
          APP_NAME="${APP_DIR//-/_}"
          IMAGE_NAME="${APP_DIR//-/}"
          echo "app_dir=$APP_DIR" >> $GITHUB_ENV
          echo "app_name=$APP_NAME" >> $GITHUB_ENV
          echo "image_name=$IMAGE_NAME" >> $GITHUB_ENV

          
      - name: character-replacement-test
        run: |
          echo $APP_DIR
          echo $APP_NAME
          echo $IMAGE_NAME
