name: main

on:
  workflow_dispatch:

jobs:
  upload-container-included-scripts:
    runs-on: ubuntu-latest
    environment: artifacts
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        app-dir: ["apple-store-connect-reporting"]
    steps:
      - name: set-env
        run: |
          APP_DIR=${{ matrix.app-dir }}
          APP_NAME="${APP_DIR//-/_}"
          IMAGE_NAME="${APP_DIR//-/}"
          echo "app_dir=$APP_DIR" >> $GITHUB_ENV
          
      - name: character-replacement-test
        run: |
          echo $APP_DIR
